# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dubbing.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'dubbing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdubbing.proto\x12\x06\x64ubtts\"D\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x12\n\nsegment_id\x18\x03 \x01(\t\"7\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x03\"X\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08src_lang\x18\x02 \x01(\t\x12\x10\n\x08tgt_lang\x18\x03 \x01(\t\x12\x12\n\nsegment_id\x18\x04 \x01(\t\"I\n\x11TranslateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x03\x12\x11\n\tcache_hit\x18\x03 \x01(\x08\"Y\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x12\n\nsegment_id\x18\x04 \x01(\t\"8\n\x12SynthesizeResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x03\"\x0f\n\rHealthRequest\"-\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2\x94\x01\n\x14TranscriptionService\x12\x43\n\nTranscribe\x12\x19.dubtts.TranscribeRequest\x1a\x1a.dubtts.TranscribeResponse\x12\x37\n\x06Health\x12\x15.dubtts.HealthRequest\x1a\x16.dubtts.HealthResponse2\x8f\x01\n\x12TranslationService\x12@\n\tTranslate\x12\x18.dubtts.TranslateRequest\x1a\x19.dubtts.TranslateResponse\x12\x37\n\x06Health\x12\x15.dubtts.HealthRequest\x1a\x16.dubtts.HealthResponse2\x90\x01\n\x10SynthesisService\x12\x43\n\nSynthesize\x12\x19.dubtts.SynthesizeRequest\x1a\x1a.dubtts.SynthesizeResponse\x12\x37\n\x06Health\x12\x15.dubtts.HealthRequest\x1a\x16.dubtts.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dubbing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=25
  _globals['_TRANSCRIBEREQUEST']._serialized_end=93
  _globals['_TRANSCRIBERESPONSE']._serialized_start=95
  _globals['_TRANSCRIBERESPONSE']._serialized_end=150
  _globals['_TRANSLATEREQUEST']._serialized_start=152
  _globals['_TRANSLATEREQUEST']._serialized_end=240
  _globals['_TRANSLATERESPONSE']._serialized_start=242
  _globals['_TRANSLATERESPONSE']._serialized_end=315
  _globals['_SYNTHESIZEREQUEST']._serialized_start=317
  _globals['_SYNTHESIZEREQUEST']._serialized_end=406
  _globals['_SYNTHESIZERESPONSE']._serialized_start=408
  _globals['_SYNTHESIZERESPONSE']._serialized_end=464
  _globals['_HEALTHREQUEST']._serialized_start=466
  _globals['_HEALTHREQUEST']._serialized_end=481
  _globals['_HEALTHRESPONSE']._serialized_start=483
  _globals['_HEALTHRESPONSE']._serialized_end=528
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=531
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=679
  _globals['_TRANSLATIONSERVICE']._serialized_start=682
  _globals['_TRANSLATIONSERVICE']._serialized_end=825
  _globals['_SYNTHESISSERVICE']._serialized_start=828
  _globals['_SYNTHESISSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
