# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import dubbing_pb2 as dubbing__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dubbing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptionServiceStub:
    """Stage workers for the streaming voice-over translation pipeline.
    Workers are stateless compute services; all coordination, ordering,
    retries, and session state live in the Redis Streams dispatchers.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/dubtts.TranscriptionService/Transcribe',
                request_serializer=dubbing__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=dubbing__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/dubtts.TranscriptionService/Health',
                request_serializer=dubbing__pb2.HealthRequest.SerializeToString,
                response_deserializer=dubbing__pb2.HealthResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer:
    """Stage workers for the streaming voice-over translation pipeline.
    Workers are stateless compute services; all coordination, ordering,
    retries, and session state live in the Redis Streams dispatchers.

    """

    def Transcribe(self, request, context):
        """Transcribe one audio segment (16 kHz mono WAV bytes) to text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=dubbing__pb2.TranscribeRequest.FromString,
                    response_serializer=dubbing__pb2.TranscribeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=dubbing__pb2.HealthRequest.FromString,
                    response_serializer=dubbing__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dubtts.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dubtts.TranscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService:
    """Stage workers for the streaming voice-over translation pipeline.
    Workers are stateless compute services; all coordination, ordering,
    retries, and session state live in the Redis Streams dispatchers.

    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.TranscriptionService/Transcribe',
            dubbing__pb2.TranscribeRequest.SerializeToString,
            dubbing__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.TranscriptionService/Health',
            dubbing__pb2.HealthRequest.SerializeToString,
            dubbing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TranslationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/dubtts.TranslationService/Translate',
                request_serializer=dubbing__pb2.TranslateRequest.SerializeToString,
                response_deserializer=dubbing__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/dubtts.TranslationService/Health',
                request_serializer=dubbing__pb2.HealthRequest.SerializeToString,
                response_deserializer=dubbing__pb2.HealthResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Translate(self, request, context):
        """Translate text between languages (server-side caching).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=dubbing__pb2.TranslateRequest.FromString,
                    response_serializer=dubbing__pb2.TranslateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=dubbing__pb2.HealthRequest.FromString,
                    response_serializer=dubbing__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dubtts.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dubtts.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.TranslationService/Translate',
            dubbing__pb2.TranslateRequest.SerializeToString,
            dubbing__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.TranslationService/Health',
            dubbing__pb2.HealthRequest.SerializeToString,
            dubbing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SynthesisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/dubtts.SynthesisService/Synthesize',
                request_serializer=dubbing__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=dubbing__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/dubtts.SynthesisService/Health',
                request_serializer=dubbing__pb2.HealthRequest.SerializeToString,
                response_deserializer=dubbing__pb2.HealthResponse.FromString,
                _registered_method=True)


class SynthesisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Synthesize text to a 16 kHz mono WAV audio segment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SynthesisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=dubbing__pb2.SynthesizeRequest.FromString,
                    response_serializer=dubbing__pb2.SynthesizeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=dubbing__pb2.HealthRequest.FromString,
                    response_serializer=dubbing__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dubtts.SynthesisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dubtts.SynthesisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SynthesisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.SynthesisService/Synthesize',
            dubbing__pb2.SynthesizeRequest.SerializeToString,
            dubbing__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dubtts.SynthesisService/Health',
            dubbing__pb2.HealthRequest.SerializeToString,
            dubbing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
